env: prob
http:
  host: 0.0.0.0
  port: 8090
security:
  secret: passwwwwwww
data:
  db:
    user:
#      driver: mysql
#      dsn: root:123456@tcp(localhost:3306)/cpa_mgt
      driver: sqlite
      dsn: storage/nunu-test.db?_busy_timeout=5000

log:
  log_level: debug
  encoding: json           # json or console
  log_path: "./storage/logs"
  error_log_name: "error.log"
  log_file_name: "server.log"
  max_backups: 30
  max_age: 7
  max_size: 1024
  compress: true
