// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"cpamgt/internal/config"
	"cpamgt/internal/pkg/log"
	"cpamgt/internal/repository"
	"cpamgt/internal/server"
	"cpamgt/pkg/app"

	"github.com/google/wire"
)

// Injectors from wire.go:

func NewWire(configConfig *config.Config, logger *log.Logger) (*app.App, func(), error) {
	db := repository.NewDB(configConfig, logger)
	migrate := server.NewMigrate(db, logger)
	appApp := newApp(migrate)
	return appApp, func() {
	}, nil
}

// wire.go:

var repositorySet = wire.NewSet(repository.NewDB)

var serverSet = wire.NewSet(server.NewMigrate)

func newApp(
	migrateServer *server.Migrate,
) *app.App {
	return app.NewApp(app.WithServer(migrateServer), app.WithName("migration"))
}
