// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"cpamgt/internal/config"
	"cpamgt/internal/handler"
	"cpamgt/internal/pkg/log"
	"cpamgt/internal/repository"
	"cpamgt/internal/router"
	"cpamgt/internal/server"
	task2 "cpamgt/internal/server/task"
	"cpamgt/internal/service"
	"cpamgt/internal/task"
	"cpamgt/pkg/app"
	"cpamgt/pkg/server/http"
	"github.com/google/wire"
)

// Injectors from wire.go:

func NewWire(configConfig *config.Config, logger *log.Logger) (*app.App, func(), error) {
	handlerHandler := handler.NewHandler(logger)
	healthHandler := handler.NewHealthHandler(handlerHandler)
	mockTask := task.NewMockTask(logger)
	db := repository.NewDB(configConfig, logger)
	repositoryRepository := repository.NewRepository(logger, db)
	transaction := repository.NewTransaction(repositoryRepository)
	serviceService := service.NewService(logger, transaction)
	tokenAccountRepository := repository.NewTokenAccountRepo(repositoryRepository)
	tokenAccountService := service.NewTokenAccountService(serviceService, tokenAccountRepository)
	codexCheckTask := task.NewCodexCheckTask(logger, tokenAccountService)
	cpaAccountService := service.NewCpaAccountService(serviceService)
	cpaTask := task.NewCpaTask(logger, cpaAccountService, tokenAccountService)
	taskServer := NewTaskServer(logger, mockTask, codexCheckTask, cpaTask)
	taskManager := task2.GetTaskManager(taskServer)
	taskManageHandler := handler.NewTaskManageHandler(handlerHandler, taskManager)
	tokenAccountHandler := handler.NewTokenAccountHandler(handlerHandler, tokenAccountService)
	cpaAccountHandler := handler.NewCpaAccountHandler(handlerHandler, cpaAccountService)
	routerDeps := &router.RouterDeps{
		Conf:         configConfig,
		Logger:       logger,
		Health:       healthHandler,
		TaskMgt:      taskManageHandler,
		TokenAccount: tokenAccountHandler,
		CpaAccount:   cpaAccountHandler,
	}
	httpServer := server.NewHTTPServer(routerDeps)
	migrate := server.NewMigrate(db, logger)
	appApp := newApp(httpServer, taskServer, migrate)
	return appApp, func() {
	}, nil
}

// wire.go:

var repositorySet = wire.NewSet(repository.NewDB, repository.NewRepository, repository.NewTransaction, repository.NewTokenAccountRepo)

var serviceSet = wire.NewSet(service.NewService, service.NewTokenAccountService, service.NewCpaAccountService)

var handlerSet = wire.NewSet(handler.NewHandler, handler.NewHealthHandler, handler.NewTaskManageHandler, handler.NewTokenAccountHandler, handler.NewCpaAccountHandler)

var serverSet = wire.NewSet(server.NewHTTPServer, server.NewMigrate)

var taskSet = wire.NewSet(task.NewMockTask, task.NewCodexCheckTask, task.NewCpaTask)

func NewTaskServer(
	logger *log.Logger,
	mockTask *task.MockTask,
	codexCheckTask *task.CodexCheckTask,
	caTask *task.CpaTask,
) *task2.TaskServer {
	taskList := []task2.Task{
		mockTask,
		codexCheckTask,
		caTask,
	}
	return task2.NewTaskServer(logger, taskList...)
}

var taskExportSet = wire.NewSet(task2.GetTaskManager)

// build App
func newApp(
	httpServer *http.Server,
	taskServer *task2.TaskServer,
	migrate *server.Migrate,

) *app.App {
	return app.NewApp(app.WithServer(httpServer, taskServer, migrate), app.WithName("demo-server"))
}
